### ISSUE TITLE
Failure to parse feature file in which all scenarios have tags

### ISSUE THREAD

**Issue by carl-hartshorn** [GivePenny/GherkinSpec#16]
The following error is thrown when attempting to parse a feature file in which all scenarios have tags:
```
[18/12/2018 16:44:31 Warning] Skipping assembly because an exception was thrown: GherkinSpec.Model.Parsing.InvalidGherkinSyntaxException: Expected a step (Given, When, Then, And, But), a Scenario or a Scenario Outline, but found '@ignore'.
   at GherkinSpec.Model.Parsing.ScenarioParser.ParseScenario(LineReader reader, IEnumerable`1 tags)
   at GherkinSpec.Model.Parsing.Parser.Parse(LineReader reader)
   at GherkinSpec.Model.Parsing.Parser.Parse(String featureText)
   at GherkinSpec.TestAdapter.TestDiscoverer.DiscoverTests(String source, Assembly assembly, IMessageLogger logger)
   at GherkinSpec.TestAdapter.TestDiscoverer.DiscoverTests(String source, IMessageLogger logger)
```

A simple feature file with which this can be reproduced is as follows:
```
Feature: Feature file in which all scenarios have tags should be parsable

@ignore
Scenario: First scenario has a tag
	Given all scenarios in the feature file have tags
	When GherkinSpec parses the feature file
	Then parsing should succeed

@ignore
Scenario: Second scenario also has a tag
	Given all scenarios in the feature file have tags
	When GherkinSpec parses the feature file
	Then parsing should succeed
```

**Comment by carl-hartshorn** [comment]
After investigation, a more accurate description of this issue is that a tagged scenario following another scenario (which may or may not have a tag) causes this error.
